## /etc/supervisor/conf.d/openfiber-worker.conf

[program:of-worker]
command=php /var/www/html/bin/worker.php
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/of-worker.log


####
# Alternativa cron
# * * * * * php /var/www/html/bin/of-worker.php >> /var/log/of-worker-cron.log 2>&1

